# render.yaml
services:
  - type: web
    name: mixpost
    env: php
    rootDirectory: .
    buildCommand: |
      composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
      npm install
      php artisan ziggy:generate
      npm run build
    startCommand: |
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_NAME
        value: Mixpost
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: mixpost-db
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: mixpost-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: mixpost-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mixpost-db
          property: password

databases:
  - name: mixpost-db
    databaseName: mixpost
    user: mixpost
    plan: free
